-- Migration 016: Add AI-related fields
-- Story 3.6: Add is_ai_generated field to challenges table

-- Add is_ai_generated field to challenges table
ALTER TABLE challenges
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS goal_id INTEGER REFERENCES goals(id) ON DELETE SET NULL;

-- Create index for AI-generated challenges
CREATE INDEX IF NOT EXISTS idx_challenges_ai_generated ON challenges(is_ai_generated);
CREATE INDEX IF NOT EXISTS idx_challenges_goal_id ON challenges(goal_id);

-- Update ai_feedback table to allow NULL submission_id (for challenge generation logs)
ALTER TABLE ai_feedback
ALTER COLUMN submission_id DROP NOT NULL;

-- Add comment
COMMENT ON COLUMN challenges.is_ai_generated IS 'Indicates whether the challenge was generated by AI';
COMMENT ON COLUMN challenges.goal_id IS 'Optional reference to the goal this challenge belongs to';
