import { useState, useEffect } from 'react';
import { apiService } from '../../services/api';
import './FeedbackHistory.css';

const FeedbackHistory = ({ challengeId }) => {
  const [feedbackHistory, setFeedbackHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [expandedIndex, setExpandedIndex] = useState(null);

  useEffect(() => {
    fetchFeedbackHistory();
  }, [challengeId]);

  const fetchFeedbackHistory = async () => {
    try {
      setLoading(true);
      const response = await apiService.ai.getChallengeFeedback(challengeId);
      setFeedbackHistory(response.data || []);
    } catch (err) {
      console.error('Failed to fetch feedback history:', err);
      setError('Failed to load feedback history');
    } finally {
      setLoading(false);
    }
  };

  const toggleExpand = (index) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  if (loading) {
    return (
      <div className="feedback-history-loading">
        Loading feedback history...
      </div>
    );
  }

  if (error) {
    return <div className="feedback-history-error">{error}</div>;
  }

  if (feedbackHistory.length === 0) {
    return (
      <div className="feedback-history-empty">
        <p>No feedback history yet. Submit your solution to get AI feedback!</p>
      </div>
    );
  }

  return (
    <div className="feedback-history">
      <h3>📚 Your Feedback History</h3>
      <p className="history-subtitle">
        Review past submissions and AI feedback
      </p>

      <div className="feedback-list">
        {feedbackHistory.map((item, index) => (
          <div key={item.submission_id || index} className="feedback-item">
            <div
              className="feedback-header"
              onClick={() => toggleExpand(index)}
            >
              <div className="feedback-meta">
                <span className="attempt-badge">
                  Attempt #{item.attempt_number}
                </span>
                <span className="date">
                  {new Date(item.submitted_at).toLocaleDateString()} at{' '}
                  {new Date(item.submitted_at).toLocaleTimeString()}
                </span>
                {item.confidence_score && (
                  <span className="confidence">
                    Score: {(item.confidence_score * 100).toFixed(0)}%
                  </span>
                )}
              </div>
              <button className="expand-btn">
                {expandedIndex === index ? '▼' : '▶'}
              </button>
            </div>

            {expandedIndex === index && (
              <div className="feedback-details">
                {item.feedback_id ? (
                  <>
                    <div className="feedback-section">
                      <h4>💬 Feedback</h4>
                      <p>{item.feedback_text}</p>
                    </div>

                    {item.strengths && item.strengths.length > 0 && (
                      <div className="feedback-section strengths">
                        <h4>💪 Strengths</h4>
                        <ul>
                          {item.strengths.map((strength, i) => (
                            <li key={i}>{strength}</li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {item.improvements && item.improvements.length > 0 && (
                      <div className="feedback-section improvements">
                        <h4>🎯 Areas for Improvement</h4>
                        <ul>
                          {item.improvements.map((improvement, i) => (
                            <li key={i}>{improvement}</li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {item.suggestions && item.suggestions.length > 0 && (
                      <div className="feedback-section suggestions">
                        <h4>💡 Suggestions</h4>
                        <ul>
                          {item.suggestions.map((suggestion, i) => (
                            <li key={i}>{suggestion}</li>
                          ))}
                        </ul>
                      </div>
                    )}

                    <div className="feedback-code">
                      <h4>📝 Your Code</h4>
                      <pre>
                        <code>{item.code}</code>
                      </pre>
                    </div>

                    {item.ai_model && (
                      <div className="feedback-meta-info">
                        <small>
                          Generated by {item.ai_model} in{' '}
                          {item.processing_time_ms}ms
                        </small>
                      </div>
                    )}
                  </>
                ) : (
                  <div className="no-feedback">
                    <p>No AI feedback available for this submission.</p>
                    <div className="feedback-code">
                      <h4>📝 Your Code</h4>
                      <pre>
                        <code>{item.code}</code>
                      </pre>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default FeedbackHistory;
